### ISSUE TITLE
DS1 - Move the "Red Box"

### ISSUE THREAD

**Issue by Bandit0s** [aumhaa/m4m8#1]
Hi,

first of all, THANKS  Great Job ... love to use my two DS1 again :D

Is it possible for you to move the grid ?

When i press & turn the upper right encoder (move Grid) nothing happens.
When i just turn it (Track Select), everything works fine - .

Sry for my bad english 

Thanks in advance

Ben

**Comment by aumhaa** [comment]
Not sure, maybe try resetting to factory defaults.  I’ll be around my DS1 tomorrow, will check for you then ;)

a

**Comment by Bandit0s** [comment]
I reset both of them to factory defaults (by livid editor) nothing changed ;)

**Comment by Bandit0s** [comment]
Other question, is there a way to change the settings of the channel knobs to "Device Control" instead of "Send control" ? 

Thanks in advance

**Comment by aumhaa** [comment]
I found the problem with both DS1 and CNTRLR, have fixed them in the current commit.  Let me know if you find anything else please, and thanks for bringing this to my attention!

If I remember correctly, the DS1 is supposed to be assigned to Device Control in its stock configuration.  I've changed it back to this behavior, and added a switch in Map.py called "KNOBS_ARE_SENDS", which, when set to True, should enable the sends behavior, but when set to False, will cause the knobs to control the first 5 parameters of the first device on the knobs corresponding track.  I must've changed it in my local version while helping someone affect the same change in their setup, and the change made it to repository by mistake.  Thanks for bringing this up :)

a

**Comment by Bandit0s** [comment]
For me everything looks fine now 👍 
If i find other issues, i will report them ;)
