### ISSUE TITLE
Change led Set for "Automation"-ON

### ISSUE THREAD

**Issue by Bandit0s** [aumhaa/m4m8#2]
Hi there,

its not a Issue a least, but is it possible to change the LED State for "Automation"-On from blinking to permanent ?

It would be great, or if you can tell me how i can just change it for my self ;)

Thanks in advance
Ben

**Comment by aumhaa** [comment]
I'm not sure which script you're referring to, but generally all those values are easily changeable in the Map.py file.  Presumably you're talking about CNTRLR, so you'd change the value in Map.py at line 286:

		AutomationOn = LividRGB.BlinkMedium.CYAN
		AutomationOff = LividRGB.CYAN

Just remove the BlinkMedium, so it looks like this:

		AutomationOn = LividRGB.CYAN
		AutomationOff = LividRGB.CYAN

a

**Comment by Bandit0s** [comment]
I use a DS1, just changed it .. perfekt 👍
