### ISSUE TITLE
Livid DS1 - Live Beta 3b compatibility 

### ISSUE THREAD

**Issue by Bandit0s** [aumhaa/m4m8#3]
Hi, 

do you have the possibilty to check on your scripts for the new Live Beta version.
Since the new Beta version, my DS1's will not be recognized.

Thanks in advance ;)

Ben

**Comment by aumhaa** [comment]
Thanks for the heads up, I'll check this out asap....I'm dealing with life drama at the moment though so it might take a couple of days before I can get to it.

**Comment by aumhaa** [comment]
I added a beta branch and fixed a few import problems.  Let me know if you have further issues, theoretically everything should work but I won't be able to check it thoroughly for a bit.  DS1 loads for me.

**Comment by Bandit0s** [comment]
I'm sorry for late reply, Also dealing with life drama :(

I tryed today with the newest beta version 3b1 (autoupdate ... )
and i does not recognized my DS1 :|

Once again, Thanks in advance

Ben

**Comment by aumhaa** [comment]
I'll have a looksee asap....haven't had a chance to download and decompile yet.

**Comment by aumhaa** [comment]
Are you sure you're testing against the beta branch?  I built against 3b1 and everything is working for me.....

**Comment by Bandit0s** [comment]
Hi, sorry for late reply again ... i'm back home now ... i updated to 3b7 now and have the same issue ...

i does no recognize my DS1 (cant see DS1 in the dropdown list from devices)

i copied over all datas (max and midi remote ... but nothing happens) 

what can i check to help ?
- a complete uninstallation (incl. max 8 and live 10 offical ? )
___

With Live 10 (Offical) everythink works fine ... so the files inside max8 folder schould not be the problem

**Comment by Bandit0s** [comment]
Shame on myselfe ... i never saw the "beta-branch" 
so sorry i'm so blind :(

But now i tested beta branch with Beta 3b7 (and today released 3b8) and its the same problem ...
Ableton do not list the DS1 (or any other Livid Controller) in the Dropdown list for Devices.

**Comment by aumhaa** [comment]
Sorry for the delay in responding, I’ve been swamped with various things.  I’ll have a chance to test this again on Thursday, doubtless a couple of betas have been delivered since I made the last changes and I haven’t had a time to decompile and diff things to find out what’s broken.  I’ll get back to you shortly, and thanks for keeping an eye on this!

a

**Comment by aumhaa** [comment]
Just pushed changes to beta branch of m4m8, please do let me know if you get things working!

a

**Comment by Bandit0s** [comment]
Yes ... big thanks ... everything fine again 👍 

Its okey if i reply again when there is another beta version which wont work ;D

**Comment by aumhaa** [comment]
Please do!  I can’t always download every beta when I’m working on other stuff, so it’s good to have someone using the betas that can double check for me.  I appreciate it!

a
