### ISSUE TITLE
Drum rack tracks

### ISSUE THREAD

**Issue by ClintH** [aumhaa/m4m8#5]
Hi!

The Base II script doesn't allow track selection/control of drum rack tracks (ie the individual tracks for each drum cell). Regular grouped tracks work fine.

Perhaps the track select buttons (above each of the touch strip) could also light a different colours to indicate whether it's a grouped/child track?

Some way of folding/unfolding regular groups or drum rack group tracks would be helpful too. Eg, button 1 + track select pad? Press and holding a track select pad? Pressing a track select pad with a certain force?

**Comment by aumhaa** [comment]
Somehow I thought I commented on this issue a long time ago.  Oops.  Feel free to contact me via mail for feature requests, I can always undertake something on a commissioned basis.
