### ISSUE TITLE
Live 10.1b12 Beta - Script is not working

### ISSUE THREAD

**Issue by Bandit0s** [aumhaa/m4m8#6]
Hi man, 

me again ;)

In Live 10.1b12 Beta the Script is not working :(

Maybe if you had some free time, you can have a look on it :)

Thanks in Advance
Ben

**Comment by aumhaa** [comment]
Don't worry, I'll have updates when 10.1 is released :)

**Comment by aumhaa** [comment]
Fixed in release version
